# .github/workflows/validate.yaml
name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: Install TurboJPEG
        run: |
          sudo apt-get update
          sudo apt-get install -y libturbojpeg0
          export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
      - uses: "home-assistant/actions/hassfest@master"
        env:
          LD_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu
      - uses: "hacs/action@main"
        with:
          repository: "luiscast84/HAIntercom"
          category: "integration"
          path: "custom_components/haintercom"