# .github/workflows/validate.yaml
name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libturbojpeg
      - uses: "home-assistant/actions/hassfest@master"
      - uses: "hacs/action@main"
        with:
          repository: "https://github.com/luiscast84/HAIntercom"
          category: "integration"
          path: "custom_components/haintercom"